soc: qcom: event_timer: Fix compilation after linux v4.9.298 merge
Commit ef2e64035f074bfeef14c28347aaec0b486a9e9f had removed the declaration of
"head" and "next" and converted them to "rb_root". Adapt the new declaration at
drivers/soc/qcom/event_timer.c

Fixes the following compilation errors:

  ../drivers/soc/qcom/event_timer.c:47:3: error: field designator 'head' does
  not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct
  timerqueue_head')
          .head = RB_ROOT,
           ^
  ../drivers/soc/qcom/event_timer.c:48:3: error: field designator 'next' does
  not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct
  timerqueue_head')
          .next = NULL,
           ^

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>
[kras: do the line wrapping work...]
Signed-off-by: Albert I <kras@raphielgang.org>
Signed-off-by: dodyirawan85 <40514988+dodyirawan85@users.noreply.github.com>